name: voice_message_example
description: Example app for the voice_message package
version: 1.0.0

publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.41.9"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  voice_message:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
